{TITLE_PAGE}
= $NAME$
$FROM$-$UNTIL$
Stand vom $TODAY$
= Projekt-Beschreibung
$DESCRIPTION$
{/TITLE_PAGE}

<<<<<
= Teilnehmer
Im folgenden werden alle Teilnehmer des Projektes aufgelistet. 
[width="100%", cols="<1,<1,<1", options="header"]
|=======================
| Name | Vorname | Art des Teilnehmers
{MEMBER_ROW}
| $ZNAME$ | $VNAME$ | $TYPE$
{/MEMBER_ROW}
|=======================


<<<<<
= Planungs-Posten
Auf dieser Seite werden die geplanten Kosten des Projektes aufgeschlüsselt. 

In den Planungs-Posten sind die Unter-Kontonummern enthalten, welche auf den 
Verwendungs-Zweck referenzieren. 

Eine Aufstellung aller Unterkonten und deren Bedeutung finden Sie im Anhang A.
[width="100%", cols="<2,>1,<3", options="header,footer"]
|=======================
| Planungs-Posten | Betrag | Beschreibung
{PLANNING_ROW}
| $NAME$ | $AMOUNT$ | $DESCRIPTION$
{/PLANNING_ROW}
{PLANNING_TOTAL}
>| Finanz-Bedarf: | $AMOUNT$ | 
{/PLANNING_TOTAL}
|=======================

<<<<<
= Projekt-Finanzierung
Auf dieser Seite wird die geplante Finanzierung des Projektes aufgeschlüsselt.

In den Eingangs-Konten sind die Unter-Kontonummern enthalten, welche auf den  Verwendungs-Zweck referenzieren.

Die hier angegebenen Finanz-Mittel werden noch nicht ausgegeben, sondern sind lediglich
für dieses Projekt reserviert. Sie stehen also für die Projekt-Laufzeit für keine anderen
Zwecke zur Verfügung. Bei Abschluß des Projektes werden übrige Finanz-Mittel anteilig 
wieder auf die Eingangs-Konten der Sponsoren zurück gestellt. 

Eine Aufstellung aller Unterkonten und deren Bedeutung finden Sie im Anhang A.

[width="100%", cols="<2,>1,<2", options="header,footer"]
|=======================
| Eingangs-Konto | Betrag | Beschreibung
{PAYMENT_ROW}
| $NAME$ | $AMOUNT$ | $DESCRIPTION$
{/PAYMENT_ROW}
{PAYMENT_TOTAL}
| noch zu finanzieren: | $AMOUNT$ | 
{/PAYMENT_TOTAL}
|=======================

<<<<<
= Ausgaben
Auf dieser Seite werden die tatsächlichen Kosten des Projektes aufgeschlüsselt.

In den Ausgangs-Konten sind die Unter-Kontonummern enthalten, welche auf den  Verwendungs-Zweck referenzieren.

Eine Aufstellung aller Unterkonten und deren Bedeutung finden Sie im Anhang A.

[width="100%", cols="<2,>1,>1,<2", options="header,footer"]
|=======================
| Ausgangs-Konto | Geplant | Ausgegeben | Beschreibung
{OUTGOING_ROW}
| $NAME$ | $PLANNED$ | $AMOUNT$ | $DESCRIPTION$
{/OUTGOING_ROW}
{OUTGOING_TOTAL}
| Gesamt-Ausgaben: | $PLANNED$ | $AMOUNT$ | 
{/OUTGOING_TOTAL}
|=======================

<<<<<
= Anhang A - Aufstellung der Unterkonten
[width="100%", cols="1, 5", options="header"]
|=======================
| Unter-Konto | Beschreibung
| 5730 | Stiftungs-Mittel
| 5731 | Co-Mittel
| 5732 | Teilnehmer-Beiträge
| 5733 | Spenden
| 5734 | Verleih-Pauschalen
| 5735 | Mitglieds-Beiträge
| 5800 | Gehälter
| 5801 | Soz. Abgaben
| 5802 | Trainer
| 5803 | Sach-Kosten
|=======================
